name: develop to main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge develop into main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge develop
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
