name: develop to main

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR from develop to main
        run: |
          EXISTING_PR=$(gh pr list --base main --head develop --json number -q '.[0].number')

          if [ -z "$EXISTING_PR" ]; then
            # PR 생성
            PR_URL=$(gh pr create --base main --head develop --title "develop -> main 릴리스" --body "develop 브랜치의 변경사항을 main 브랜치로 자동 머지")
            echo "PR 생성됨: $PR_URL"
          else
            echo "PR이 이미 존재합니다: #$EXISTING_PR"
          fi
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_PAT }}
