name: develop to main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Squash merge develop into main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # 가장 최근 머지된 PR의 제목 가져오기
          PR_TITLE=$(gh pr list --base develop --state merged --limit 1 --json title --jq '.[0].title')

          git checkout main
          git merge --squash develop
          git commit -m "$PR_TITLE"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
